"""Tests for `todolist-sorter init`."""
from pathlib import Path

import pytest
from click.testing import CliRunner

from app.cli import cli


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

_PROMPTS = "\n".join([
    "my-client-id",          # Todoist Client ID
    "my-client-secret",      # Todoist Client Secret
    "my-api-token",          # Todoist personal API token
    "",                      # LLM model (accept default)
    "my-llm-key",            # LLM API key
    "",                      # Database URL (accept default)
    "",                      # Debounce seconds (accept default)
    "",                      # Suppression window (accept default)
]) + "\n"


# ---------------------------------------------------------------------------
# Basic happy path
# ---------------------------------------------------------------------------


def test_init_creates_env_file(tmp_path):
    output = tmp_path / ".env"
    runner = CliRunner()
    result = runner.invoke(
        cli,
        ["init", "--output", str(output)],
        input=_PROMPTS,
    )
    assert result.exit_code == 0, result.output
    assert output.exists()


def test_init_env_contains_expected_keys(tmp_path):
    output = tmp_path / ".env"
    runner = CliRunner()
    result = runner.invoke(
        cli,
        ["init", "--output", str(output)],
        input=_PROMPTS,
    )
    assert result.exit_code == 0
    content = output.read_text(encoding="utf-8")
    for key in (
        "TODOIST_CLIENT_ID",
        "TODOIST_CLIENT_SECRET",
        "TODOIST_API_TOKEN",
        "LLM_MODEL",
        "LLM_API_KEY",
        "APP_API_KEY",
        "DATABASE_URL",
        "DEFAULT_DEBOUNCE_SECONDS",
        "SUPPRESSION_WINDOW_SECONDS",
    ):
        assert key in content, f"Expected {key} in generated .env"


def test_init_app_api_key_is_auto_generated_and_long(tmp_path):
    output = tmp_path / ".env"
    runner = CliRunner()
    result = runner.invoke(
        cli,
        ["init", "--output", str(output)],
        input=_PROMPTS,
    )
    assert result.exit_code == 0
    content = output.read_text(encoding="utf-8")
    # Parse out APP_API_KEY
    for line in content.splitlines():
        if line.startswith("APP_API_KEY="):
            key_val = line.split("=", 1)[1]
            assert len(key_val) >= 32, f"APP_API_KEY too short: {key_val!r}"
            break
    else:
        pytest.fail("APP_API_KEY not found in generated .env")


def test_init_contains_header_comment(tmp_path):
    output = tmp_path / ".env"
    runner = CliRunner()
    result = runner.invoke(
        cli,
        ["init", "--output", str(output)],
        input=_PROMPTS,
    )
    assert result.exit_code == 0
    content = output.read_text(encoding="utf-8")
    assert content.startswith("# Generated by todolist-sorter init on ")


def test_init_env_is_parseable_as_dotenv(tmp_path):
    """Each non-comment line must be KEY=value."""
    output = tmp_path / ".env"
    runner = CliRunner()
    result = runner.invoke(
        cli,
        ["init", "--output", str(output)],
        input=_PROMPTS,
    )
    assert result.exit_code == 0
    for line in output.read_text(encoding="utf-8").splitlines():
        if not line or line.startswith("#"):
            continue
        assert "=" in line, f"Non-parseable line: {line!r}"


# ---------------------------------------------------------------------------
# Overwrite / --force
# ---------------------------------------------------------------------------


def test_init_existing_file_prompts_confirm(tmp_path):
    output = tmp_path / ".env"
    output.write_text("OLD=value\n", encoding="utf-8")
    runner = CliRunner()
    # Say "n" to overwrite prompt → abort
    result = runner.invoke(
        cli,
        ["init", "--output", str(output)],
        input="n\n",
    )
    assert result.exit_code != 0
    # File should remain unchanged
    assert output.read_text(encoding="utf-8") == "OLD=value\n"


def test_init_existing_file_confirm_yes_overwrites(tmp_path):
    output = tmp_path / ".env"
    output.write_text("OLD=value\n", encoding="utf-8")
    runner = CliRunner()
    # Say "y" first (overwrite prompt), then supply all prompts
    result = runner.invoke(
        cli,
        ["init", "--output", str(output)],
        input="y\n" + _PROMPTS,
    )
    assert result.exit_code == 0
    assert "TODOIST_CLIENT_ID" in output.read_text(encoding="utf-8")


def test_init_force_flag_overwrites_without_prompt(tmp_path):
    output = tmp_path / ".env"
    output.write_text("OLD=value\n", encoding="utf-8")
    runner = CliRunner()
    result = runner.invoke(
        cli,
        ["init", "--output", str(output), "--force"],
        input=_PROMPTS,
    )
    assert result.exit_code == 0
    content = output.read_text(encoding="utf-8")
    assert "TODOIST_CLIENT_ID" in content
    assert "OLD=value" not in content


# ---------------------------------------------------------------------------
# Works without TODOLIST_SORTER_API_KEY env var
# ---------------------------------------------------------------------------


def test_init_works_without_api_key_env(tmp_path):
    """init must not require TODOLIST_SORTER_API_KEY."""
    output = tmp_path / ".env"
    runner = CliRunner()
    result = runner.invoke(
        cli,
        ["init", "--output", str(output)],
        input=_PROMPTS,
        env={},  # explicitly empty env
    )
    assert result.exit_code == 0


def test_init_uses_default_llm_model(tmp_path):
    output = tmp_path / ".env"
    runner = CliRunner()
    result = runner.invoke(
        cli,
        ["init", "--output", str(output)],
        input=_PROMPTS,  # accepts default for LLM model
    )
    assert result.exit_code == 0
    content = output.read_text(encoding="utf-8")
    assert "anthropic:claude-sonnet-4-6" in content
